---
name: test
on:
  pull_request:
    branches: master
jobs:
  tests:
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@v2
      - name: Install package.
        run: pip install -e .
      - name: Install test dependencies.
        run: pip install pytest
      - name: Run the tests
        run: pytest
  build:
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@v2
      - name: Install package.
        run: pip install .
      - name: Build the test site.
        run: aip-site-gen tests/test_data/ /out/
  lint:
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@v2
      - name: Install the linter (flake8).
        run: pip install flake8
      - name: Run the linter.
        run: flake8 aip_site/ tests/
  mypy:
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - uses: actions/checkout@v2
      - name: Install package.
        run: pip install .
      - name: Install mypy.
        run: pip install mypy
      - name: Run mypy.
        run: mypy aip_site
